---
- hosts: wind
  tasks: 
    - name: Create a file
      win_file:
        path: C:\Users\Administrator\Desktop\Win_test
        state: directory
    - name: Download file from online
      win_get_url: 
        dest: C:\Users\Administrator\Desktop\Win_test
        url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.3.tar.xz
    - name: Update all packages
      win_updates:
        category_names: '*'  
        reboot: true
